import { createFileRoute } from "@tanstack/react-router";
import { CheckCircle2, Plus, Printer, ReceiptText, Wallet, X } from "lucide-react";
import { useState, type FormEvent } from "react";

import { Button } from "@/components/ui/button";
import { SchoolShell } from "@/components/school-shell";

export const Route = createFileRoute("/finance")({ head: () => ({ meta: [{ title: "Finance — Harrow Green" }, { name: "description", content: "Record school payments and issue receipts." }] }), component: FinancePage });

type PaymentStatus = "verified" | "pending";
type Payment = { receipt: string; student: string; fee: string; amount: number; method: string; date: string; status: PaymentStatus; providerReference: string };
const initialPayments: Payment[] = [
  { receipt: "HGA-240514-041", student: "Ama Mensah", fee: "School fees", amount: 350, method: "Mobile money", date: "Today, 09:42", status: "verified", providerReference: "PSK-7J4M-18A" },
  { receipt: "HGA-240514-040", student: "Kwame Asare", fee: "Daily payment", amount: 20, method: "Mobile money", date: "Today, 09:15", status: "verified", providerReference: "PSK-5C2R-04D" },
  { receipt: "HGA-240514-039", student: "Esi Owusu", fee: "Examination fee", amount: 75, method: "Card", date: "Today, 08:54", status: "verified", providerReference: "PSK-9K1P-72B" },
];

function FinancePage() {
  const [payments, setPayments] = useState(initialPayments);
  const [showForm, setShowForm] = useState(false);
  const [receipt, setReceipt] = useState<Payment | null>(null);
  const [student, setStudent] = useState("");
  const [fee, setFee] = useState("Daily payment");
  const [amount, setAmount] = useState("");
  const [method, setMethod] = useState("Mobile money");

  function savePayment(event: FormEvent) {
    event.preventDefault();
    const value = Number(amount);
    if (!student.trim() || !Number.isFinite(value) || value <= 0) return;
    const payment = { receipt: `HGA-${String(payments.length + 42).padStart(3, "0")}`, student: student.trim(), fee, amount: value, method, date: "Just now", status: "pending" as const, providerReference: `DEMO-${crypto.randomUUID().slice(0, 8).toUpperCase()}` };
    setPayments((current) => [payment, ...current]); setStudent(""); setAmount(""); setShowForm(false);
  }

  function markVerified(receipt: string) { setPayments((current) => current.map((payment) => payment.receipt === receipt ? { ...payment, status: "verified" } : payment)); }

  return <SchoolShell title="Finance"><div className="mx-auto max-w-6xl rise">
    <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="mb-3 grid size-10 place-items-center rounded-md bg-secondary text-secondary-foreground ring-1 ring-border"><Wallet className="size-5" /></div><h1 className="font-display text-3xl font-bold">Finance desk</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Create payment requests for daily payments and school fees. Receipts are issued only after provider verification.</p></div><Button onClick={() => setShowForm(true)}><Plus />Create payment request</Button></div>
    <div className="mt-4 rounded-md border border-primary/15 bg-primary/5 px-4 py-3 text-sm text-secondary-foreground"><strong>Verification rule:</strong> a payment request is not money received. Only a verified gateway callback can unlock its receipt. Provider references and receipt numbers are unique and cannot be reused.</div>
    <section className="mt-7 grid gap-3 sm:grid-cols-3"><Metric label="Collected today" value="GH₵ 2,840" note="18 payments received" /><Metric label="School fees" value="GH₵ 1,960" note="Today’s fee collection" /><Metric label="Receipts issued" value={String(payments.length + 38)} note="This week" /></section>
    <section className="glass-panel mt-4 overflow-hidden rounded-lg"><div className="flex items-center justify-between border-b border-border px-5 py-4"><div><h2 className="font-display text-lg font-bold">Recent payment requests</h2><p className="mt-1 text-xs text-muted-foreground">Provider references are unique; a receipt is available only after verification.</p></div><ReceiptText className="size-5 text-primary" /></div><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-sm"><thead className="bg-muted/60 text-xs text-muted-foreground"><tr><th className="px-5 py-3 font-medium">Provider reference</th><th className="px-5 py-3 font-medium">Student</th><th className="px-5 py-3 font-medium">Fee type</th><th className="px-5 py-3 font-medium">Amount</th><th className="px-5 py-3 font-medium">Status</th><th className="px-5 py-3 font-medium">Action</th></tr></thead><tbody className="divide-y divide-border/70">{payments.map((payment) => <tr key={payment.receipt}><td className="px-5 py-4 font-mono text-xs text-secondary-foreground">{payment.providerReference}</td><td className="px-5 py-4 font-medium">{payment.student}</td><td className="px-5 py-4">{payment.fee}</td><td className="px-5 py-4">GH₵ {payment.amount.toFixed(2)}</td><td className="px-5 py-4"><span className={payment.status === "verified" ? "inline-flex items-center gap-1 rounded-full bg-emerald-500/10 px-2 py-1 text-xs font-medium text-emerald-700" : "inline-flex rounded-full bg-amber-500/10 px-2 py-1 text-xs font-medium text-amber-700"}>{payment.status === "verified" && <CheckCircle2 className="size-3.5" />}{payment.status === "verified" ? "Verified" : "Awaiting gateway"}</span></td><td className="px-5 py-4">{payment.status === "verified" ? <Button size="sm" variant="outline" onClick={() => setReceipt(payment)}><Printer />Receipt</Button> : <Button size="sm" variant="outline" onClick={() => markVerified(payment.receipt)}>Test gateway callback</Button>}</td></tr>)}</tbody></table></div></section>
  </div>{showForm && <PaymentForm student={student} setStudent={setStudent} fee={fee} setFee={setFee} amount={amount} setAmount={setAmount} method={method} setMethod={setMethod} onClose={() => setShowForm(false)} onSubmit={savePayment} />}{receipt && <Receipt payment={receipt} onClose={() => setReceipt(null)} />}</SchoolShell>;
}

function PaymentForm({ student, setStudent, fee, setFee, amount, setAmount, method, setMethod, onClose, onSubmit }: { student: string; setStudent: (value: string) => void; fee: string; setFee: (value: string) => void; amount: string; setAmount: (value: string) => void; method: string; setMethod: (value: string) => void; onClose: () => void; onSubmit: (event: FormEvent) => void }) { const inputClass = "h-10 w-full rounded-md border border-input bg-background/70 px-3 outline-none focus:ring-2 focus:ring-ring"; return <div className="fixed inset-0 z-50 grid place-items-center bg-foreground/30 p-4 backdrop-blur-sm"><form onSubmit={onSubmit} className="glass-panel w-full max-w-md rounded-lg p-6 shadow-2xl"><div className="flex items-start justify-between"><div><h2 className="font-display text-xl font-bold">Create payment request</h2><p className="mt-1 text-sm text-muted-foreground">A receipt becomes available only after a verified gateway callback.</p></div><Button type="button" variant="ghost" size="icon" onClick={onClose} aria-label="Close"><X /></Button></div><Field label="Student"><input required value={student} onChange={(event) => setStudent(event.target.value)} placeholder="Student name or admission number" className={inputClass} /></Field><div className="mt-4 grid grid-cols-2 gap-3"><Field label="Fee type"><select value={fee} onChange={(event) => setFee(event.target.value)} className={inputClass}>{["Daily payment", "School fees", "Examination fee", "Other fee"].map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="Amount (GH₵)"><input required min="0.01" step="0.01" type="number" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="0.00" className={inputClass} /></Field></div><Field label="Electronic payment channel"><select value={method} onChange={(event) => setMethod(event.target.value)} className={inputClass}>{["Mobile money", "Card", "Bank transfer"].map((item) => <option key={item}>{item}</option>)}</select></Field><div className="mt-6 flex justify-end gap-2"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button type="submit">Create payment request</Button></div></form></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="mt-4 block text-sm"><span className="mb-1.5 block text-xs font-medium text-muted-foreground">{label}</span>{children}</label>; }
function Receipt({ payment, onClose }: { payment: Payment; onClose: () => void }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-foreground/30 p-4 backdrop-blur-sm"><div className="glass-panel w-full max-w-md rounded-lg p-6 shadow-2xl"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2 text-emerald-700"><CheckCircle2 className="size-5" /><span className="text-sm font-medium">Payment recorded</span></div><h2 className="mt-3 font-display text-xl font-bold">Payment receipt</h2></div><Button variant="ghost" size="icon" onClick={onClose} aria-label="Close"><X /></Button></div><div className="mt-5 rounded-md border border-border bg-background/70 p-4 text-sm"><p className="font-display text-base font-bold">Harrow Green Academy</p><p className="mt-1 font-mono text-xs text-muted-foreground">{payment.receipt}</p><dl className="mt-5 space-y-3"><Row label="Student" value={payment.student} /><Row label="Payment for" value={payment.fee} /><Row label="Method" value={payment.method} /><Row label="Date" value={payment.date} /><Row label="Amount paid" value={`GH₵ ${payment.amount.toFixed(2)}`} /></dl></div><div className="mt-5 flex justify-end gap-2"><Button variant="outline" onClick={onClose}>Done</Button><Button onClick={() => printReceipt(payment)}><Printer />Print / save PDF</Button></div></div></div>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-4"><dt className="text-muted-foreground">{label}</dt><dd className="text-right font-medium">{value}</dd></div>; }
function printReceipt(payment: Payment) { const receiptWindow = window.open("", "_blank"); if (!receiptWindow) return; const safe = (value: string) => value.replace(/[&<>\"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[character] ?? character); receiptWindow.document.write(`<html><head><title>${safe(payment.receipt)}</title><style>body{font:14px Arial;padding:32px;color:#16251e}h1{font:700 22px Georgia}table{width:100%;border-collapse:collapse;margin-top:24px}td{padding:10px 0;border-bottom:1px solid #ddd}td:last-child{text-align:right;font-weight:600}</style></head><body><h1>Harrow Green Academy</h1><p>Official payment receipt</p><p>Receipt: ${safe(payment.receipt)}</p><table><tr><td>Student</td><td>${safe(payment.student)}</td></tr><tr><td>Payment for</td><td>${safe(payment.fee)}</td></tr><tr><td>Method</td><td>${safe(payment.method)}</td></tr><tr><td>Date</td><td>${safe(payment.date)}</td></tr><tr><td>Amount paid</td><td>GH₵ ${payment.amount.toFixed(2)}</td></tr></table><p>Thank you for your payment.</p><script>window.print()</script></body></html>`); receiptWindow.document.close(); }
function Metric({ label, value, note }: { label: string; value: string; note: string }) { return <article className="glass-panel rounded-lg p-5"><p className="text-xs font-medium text-muted-foreground">{label}</p><p className="mt-2 font-display text-3xl">{value}</p><p className="mt-1 text-xs text-secondary-foreground">{note}</p></article>; }
