import { createFileRoute } from "@tanstack/react-router";
import { Bell, CreditCard, GraduationCap, HeartHandshake, ReceiptText, UserRoundCheck } from "lucide-react";
import { useState } from "react";

import { Button } from "@/components/ui/button";
import { SchoolShell } from "@/components/school-shell";

export const Route = createFileRoute("/parent")({ head: () => ({ meta: [{ title: "Parent Portal — Harrow Green" }, { name: "description", content: "Follow your children’s learning, attendance, and fees." }] }), component: ParentPortal });

const children = [
  { name: "Ama Mensah", className: "Form 1A", attendance: "96%", average: "78%", balance: 120, notice: "Science project due Friday" },
  { name: "Kojo Mensah", className: "Form 3C", attendance: "93%", average: "82%", balance: 220, notice: "Terminal results published" },
];

function ParentPortal() {
  const [paying, setPaying] = useState(false);
  return <SchoolShell title="My children" parentPortal><div className="mx-auto max-w-6xl rise">
    <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="mb-3 grid size-10 place-items-center rounded-md bg-secondary text-secondary-foreground ring-1 ring-border"><HeartHandshake className="size-5" /></div><h1 className="font-display text-3xl font-bold">Good afternoon, Mrs. Mensah</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Keep up with your children’s attendance, learning progress, school notices, and fee balances.</p></div><Button onClick={() => setPaying(true)}><CreditCard />Pay fees</Button></div>
    <section className="mt-7 grid gap-3 sm:grid-cols-3"><Metric label="Children" value="2" note="Forms 1A and 3C" /><Metric label="Outstanding balance" value="GH₵ 340" note="Across both children" /><Metric label="New notices" value="3" note="2 need your attention" /></section>
    <section className="mt-4 grid gap-4 lg:grid-cols-2">{children.map((child) => <article key={child.name} className="glass-panel rounded-lg p-5"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-md bg-primary/10 text-primary"><GraduationCap className="size-5" /></div><div><h2 className="font-display text-lg font-bold">{child.name}</h2><p className="text-xs text-muted-foreground">{child.className}</p></div></div><span className={child.balance > 0 ? "rounded-full bg-amber-500/10 px-2 py-1 text-xs font-medium text-amber-700" : "rounded-full bg-emerald-500/10 px-2 py-1 text-xs font-medium text-emerald-700"}>{child.balance > 0 ? `GH₵ ${child.balance} due` : "Paid"}</span></div><div className="mt-5 grid grid-cols-2 gap-3"><SmallStat icon={UserRoundCheck} label="Attendance" value={child.attendance} /><SmallStat icon={GraduationCap} label="Term average" value={child.average} /></div><div className="mt-4 flex items-start gap-2 border-t border-border pt-4 text-xs text-secondary-foreground"><Bell className="mt-0.5 size-3.5 shrink-0 text-primary" />{child.notice}</div></article>)}</section>
    <section className="glass-panel mt-4 overflow-hidden rounded-lg"><div className="flex items-center justify-between border-b border-border px-5 py-4"><div><h2 className="font-display text-lg font-bold">Recent payment activity</h2><p className="mt-1 text-xs text-muted-foreground">Receipts remain available whenever you need them.</p></div><ReceiptText className="size-5 text-primary" /></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-muted/60 text-xs text-muted-foreground"><tr><th className="px-5 py-3 font-medium">Receipt</th><th className="px-5 py-3 font-medium">Child</th><th className="px-5 py-3 font-medium">Payment</th><th className="px-5 py-3 font-medium">Amount</th></tr></thead><tbody className="divide-y divide-border/70"><tr><td className="px-5 py-4 font-mono text-xs">HGA-240510-018</td><td className="px-5 py-4 font-medium">Ama Mensah</td><td className="px-5 py-4">School fees</td><td className="px-5 py-4">GH₵ 300.00</td></tr><tr><td className="px-5 py-4 font-mono text-xs">HGA-240503-009</td><td className="px-5 py-4 font-medium">Kojo Mensah</td><td className="px-5 py-4">Examination fee</td><td className="px-5 py-4">GH₵ 75.00</td></tr></tbody></table></div></section>
  </div>{paying && <PaymentPanel onClose={() => setPaying(false)} />}</SchoolShell>;
}

function PaymentPanel({ onClose }: { onClose: () => void }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-foreground/30 p-4 backdrop-blur-sm"><div className="glass-panel w-full max-w-md rounded-lg p-6 shadow-2xl"><CreditCard className="size-6 text-primary" /><h2 className="mt-4 font-display text-xl font-bold">Pay school fees</h2><p className="mt-2 text-sm text-muted-foreground">Online payment will be connected to the school’s approved payment provider. Your current outstanding balance is GH₵ 340.00.</p><div className="mt-5 rounded-md border border-border bg-background/70 p-4 text-sm"><p className="font-medium">Payment options</p><p className="mt-1 text-muted-foreground">Mobile money, card, or bank transfer</p></div><div className="mt-6 flex justify-end gap-2"><Button variant="outline" onClick={onClose}>Not now</Button><Button onClick={onClose}>Continue to payment</Button></div></div></div>; }
function Metric({ label, value, note }: { label: string; value: string; note: string }) { return <article className="glass-panel rounded-lg p-5"><p className="text-xs font-medium text-muted-foreground">{label}</p><p className="mt-2 font-display text-3xl">{value}</p><p className="mt-1 text-xs text-secondary-foreground">{note}</p></article>; }
function SmallStat({ icon: Icon, label, value }: { icon: typeof UserRoundCheck; label: string; value: string }) { return <div className="rounded-md bg-secondary/45 p-3"><Icon className="size-4 text-primary" /><p className="mt-2 text-xs text-muted-foreground">{label}</p><p className="mt-0.5 font-display text-lg">{value}</p></div>; }
