import { createFileRoute } from "@tanstack/react-router";
import { CheckCircle2, CircleAlert, FileCheck2, Landmark, ShieldCheck, Smartphone, X } from "lucide-react";
import { useState } from "react";

import { Button } from "@/components/ui/button";
import { SchoolShell } from "@/components/school-shell";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/reconciliation")({
  head: () => ({ meta: [{ title: "Daily Reconciliation — Harrow Green" }, { name: "description", content: "Review gateway-verified collections and payment exceptions." }] }),
  component: ReconciliationPage,
});

type Exception = { id: string; student: string; className: string; issue: string; owner: string; severity: "Review" | "Pending" | "Info"; status: "Open" | "Investigating" | "Resolved"; due: string; note?: string };
const initialExceptions: Exception[] = [];

function ReconciliationPage() {
  const [closed, setClosed] = useState(false);
  const [exceptions, setExceptions] = useState(initialExceptions);
  const [resolving, setResolving] = useState<Exception | null>(null);
  const [resolutionNote, setResolutionNote] = useState("");
  function assignException(id: string, owner: string) { setExceptions((current) => current.map((exception) => exception.id === id ? { ...exception, owner, status: exception.status === "Open" ? "Investigating" : exception.status } : exception)); }
  function resolveException() { if (!resolving || !resolutionNote.trim()) return; setExceptions((current) => current.map((exception) => exception.id === resolving.id ? { ...exception, status: "Resolved", note: resolutionNote.trim() } : exception)); setResolutionNote(""); setResolving(null); }
  return <SchoolShell title="Daily reconciliation" schoolAdmin><div className="mx-auto max-w-6xl rise">
    <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="mb-3 grid size-10 place-items-center rounded-md bg-secondary text-secondary-foreground ring-1 ring-border"><ShieldCheck className="size-5" /></div><h1 className="font-display text-3xl font-bold">Daily reconciliation</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Compare gateway-confirmed collections with attendance and resolve exceptions before closing the day.</p></div><Button disabled={closed || exceptions.length === 0} onClick={() => setClosed(true)}>{closed ? <><CheckCircle2 />Day closed</> : <><FileCheck2 />Close today</>}</Button></div>
    <section className="mt-7 grid gap-3 sm:grid-cols-3"><Metric label="Expected today" value="—" note="Live payment data not connected" /><Metric label="Received today" value="—" note="Live payment data not connected" /><Metric label="Variance" value="—" note="Live payment data not connected" tone="warning" /></section>
    <section className="mt-4 grid gap-4 lg:grid-cols-5"><article className="glass-panel rounded-lg p-5 lg:col-span-3"><div className="flex items-center justify-between"><div><h2 className="font-display text-lg font-bold">Collection channels</h2><p className="mt-1 text-xs text-muted-foreground">Only verified provider events count toward collections.</p></div><Smartphone className="size-5 text-primary" /></div><p className="mt-5 text-sm text-muted-foreground">Channel totals will appear when live payment records are connected.</p></article><article className="glass-panel rounded-lg p-5 lg:col-span-2"><Landmark className="size-5 text-primary" /><h2 className="mt-3 font-display text-lg font-bold">Close-day control</h2><p className="mt-1 text-sm text-muted-foreground">Closing the day is unavailable until live payment and attendance data are connected.</p><div className={cn("mt-5 rounded-md px-3 py-2 text-sm", closed ? "bg-emerald-500/10 text-emerald-700" : "bg-amber-500/10 text-amber-700")}>{closed ? "Day closed." : "Live reconciliation data is not connected."}</div></article></section>
    <section className="glass-panel mt-4 overflow-hidden rounded-lg"><div className="flex items-center justify-between border-b border-border px-5 py-4"><div><h2 className="font-display text-lg font-bold">Payment and attendance exceptions</h2><p className="mt-1 text-xs text-muted-foreground">Assign an owner and resolve every exception with an audit note.</p></div><CircleAlert className="size-5 text-amber-600" /></div><div className="overflow-x-auto"><table className="w-full min-w-[920px] text-left text-sm"><thead className="bg-muted/60 text-xs text-muted-foreground"><tr><th className="px-5 py-3 font-medium">Student</th><th className="px-5 py-3 font-medium">Exception</th><th className="px-5 py-3 font-medium">Owner</th><th className="px-5 py-3 font-medium">Due</th><th className="px-5 py-3 font-medium">Status</th><th className="px-5 py-3 font-medium">Action</th></tr></thead><tbody className="divide-y divide-border/70">{exceptions.map((item) => <tr key={item.id} className="hover:bg-muted/30"><td className="px-5 py-4"><p className="font-medium">{item.student}</p><p className="text-xs text-muted-foreground">{item.className}</p></td><td className="px-5 py-4">{item.issue}{item.note && <p className="mt-1 text-xs text-muted-foreground">Resolved: {item.note}</p>}</td><td className="px-5 py-4"><select disabled={item.status === "Resolved"} value={item.owner} onChange={(event) => assignException(item.id, event.target.value)} className="h-8 rounded-md border border-input bg-background px-2 text-xs outline-none disabled:opacity-60"><option>Finance</option><option>School Admin</option><option>Gateway</option></select></td><td className="px-5 py-4 text-xs">{item.due}</td><td className="px-5 py-4"><StatusBadge value={item.status} /></td><td className="px-5 py-4">{item.status === "Resolved" ? <Badge value={item.severity} /> : <Button size="sm" variant="outline" onClick={() => setResolving(item)}>Resolve</Button>}</td></tr>)}{exceptions.length === 0 && <tr><td colSpan={6} className="px-5 py-10 text-center text-sm text-muted-foreground">No exceptions are available. Live attendance and payment data are not connected.</td></tr>}</tbody></table></div></section>
  </div>{resolving && <ResolveDialog item={resolving} note={resolutionNote} setNote={setResolutionNote} onClose={() => { setResolving(null); setResolutionNote(""); }} onResolve={resolveException} />}</SchoolShell>;
}
function Badge({ value }: { value: string }) { return <span className={cn("rounded-full px-2 py-1 text-xs font-medium", value === "Info" ? "bg-primary/10 text-primary" : value === "Pending" ? "bg-amber-500/10 text-amber-700" : "bg-rose-500/10 text-rose-700")}>{value}</span>; }
function StatusBadge({ value }: { value: Exception["status"] }) { return <span className={cn("rounded-full px-2 py-1 text-xs font-medium", value === "Resolved" ? "bg-emerald-500/10 text-emerald-700" : value === "Investigating" ? "bg-primary/10 text-primary" : "bg-amber-500/10 text-amber-700")}>{value}</span>; }
function ResolveDialog({ item, note, setNote, onClose, onResolve }: { item: Exception; note: string; setNote: (value: string) => void; onClose: () => void; onResolve: () => void }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-foreground/30 p-4 backdrop-blur-sm"><div className="glass-panel w-full max-w-md rounded-lg p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><h2 className="font-display text-xl font-bold">Resolve exception</h2><p className="mt-1 text-sm text-muted-foreground">{item.student}: {item.issue}</p></div><Button variant="ghost" size="icon" onClick={onClose} aria-label="Close"><X /></Button></div><label className="mt-5 block text-sm"><span className="mb-1.5 block text-xs font-medium text-muted-foreground">Resolution note</span><textarea required value={note} onChange={(event) => setNote(event.target.value)} placeholder="Explain what was checked and why this exception is resolved." className="min-h-24 w-full rounded-md border border-input bg-background/70 p-3 text-sm outline-none focus:ring-2 focus:ring-ring" /></label><div className="mt-6 flex justify-end gap-2"><Button variant="outline" onClick={onClose}>Cancel</Button><Button disabled={!note.trim()} onClick={onResolve}>Resolve & log note</Button></div></div></div>; }
function Metric({ label, value, note, tone }: { label: string; value: string; note: string; tone?: "warning" }) { return <article className={cn("glass-panel rounded-lg p-5", tone === "warning" && "ring-1 ring-amber-500/25")}><p className="text-xs font-medium text-muted-foreground">{label}</p><p className={cn("mt-2 font-display text-3xl", tone === "warning" && "text-amber-700")}>{value}</p><p className="mt-1 text-xs text-secondary-foreground">{note}</p></article>; }
