import { createFileRoute } from "@tanstack/react-router";
import { Bell, BookOpenCheck, CalendarDays, CreditCard, GraduationCap, UserRoundCheck } from "lucide-react";
import { useState } from "react";

import { Button } from "@/components/ui/button";
import { SchoolShell } from "@/components/school-shell";

export const Route = createFileRoute("/student")({ head: () => ({ meta: [{ title: "Student Portal — Klasora" }, { name: "description", content: "Follow your learning, attendance, results, and school notices." }] }), component: StudentPortal });

const results = [{ subject: "English Language", score: "82%", grade: "A" }, { subject: "Mathematics", score: "74%", grade: "B" }, { subject: "Integrated Science", score: "79%", grade: "B+" }, { subject: "Social Studies", score: "86%", grade: "A" }];
const lessons = [{ time: "08:00", subject: "Mathematics", room: "Room 4" }, { time: "10:15", subject: "Integrated Science", room: "Lab 1" }, { time: "12:30", subject: "English Language", room: "Room 4" }];

function StudentPortal() {
  const [showResults, setShowResults] = useState(false);
  return <SchoolShell title="My learning" studentPortal><div className="mx-auto max-w-6xl rise">
    <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="mb-3 grid size-10 place-items-center rounded-md bg-secondary text-secondary-foreground ring-1 ring-border"><GraduationCap className="size-5" /></div><h1 className="font-display text-3xl font-bold">Good morning, Ama</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Form 1A · Term II. Stay on top of your classes, results, attendance, and school updates.</p></div><Button onClick={() => setShowResults(true)}><BookOpenCheck />View results</Button></div>
    <section className="mt-7 grid gap-3 sm:grid-cols-3"><Metric label="Attendance" value="96%" note="Present 62 of 65 days" /><Metric label="Term average" value="78%" note="Across 6 subjects" /><Metric label="Fee balance" value="GH₵ 120" note="Ask a parent to pay" /></section>
    <section className="mt-4 grid gap-4 lg:grid-cols-5"><article className="glass-panel rounded-lg p-5 lg:col-span-3"><div className="flex items-center justify-between"><div><h2 className="font-display text-lg font-bold">Today&apos;s lessons</h2><p className="mt-1 text-xs text-muted-foreground">Tuesday, 14 May · Form 1A</p></div><CalendarDays className="size-5 text-primary" /></div><div className="mt-5 divide-y divide-border/70">{lessons.map((lesson) => <div key={lesson.time} className="flex items-center justify-between py-3"><div className="flex items-center gap-3"><span className="font-mono text-xs text-muted-foreground">{lesson.time}</span><div><p className="font-medium">{lesson.subject}</p><p className="text-xs text-muted-foreground">{lesson.room}</p></div></div><span className="rounded-full bg-primary/10 px-2 py-1 text-xs text-primary">Scheduled</span></div>)}</div></article><article className="glass-panel rounded-lg p-5 lg:col-span-2"><Bell className="size-5 text-primary" /><h2 className="mt-3 font-display text-lg font-bold">Latest notice</h2><p className="mt-2 text-sm text-secondary-foreground">Science project presentations begin on Friday. Bring your completed display board to the lab by 08:00.</p><p className="mt-4 text-xs text-muted-foreground">Posted by Mr. Okoye · Yesterday</p></article></section>
    <section className="glass-panel mt-4 overflow-hidden rounded-lg"><div className="flex items-center justify-between border-b border-border px-5 py-4"><div><h2 className="font-display text-lg font-bold">Subject performance</h2><p className="mt-1 text-xs text-muted-foreground">Your latest continuous-assessment scores.</p></div><BookOpenCheck className="size-5 text-primary" /></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-muted/60 text-xs text-muted-foreground"><tr><th className="px-5 py-3 font-medium">Subject</th><th className="px-5 py-3 font-medium">Latest score</th><th className="px-5 py-3 font-medium">Grade</th><th className="px-5 py-3 font-medium">Progress</th></tr></thead><tbody className="divide-y divide-border/70">{results.map((result) => <tr key={result.subject}><td className="px-5 py-4 font-medium">{result.subject}</td><td className="px-5 py-4">{result.score}</td><td className="px-5 py-4"><span className="rounded-full bg-emerald-500/10 px-2 py-1 text-xs font-medium text-emerald-700">{result.grade}</span></td><td className="px-5 py-4"><div className="h-2 w-32 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: result.score }} /></div></td></tr>)}</tbody></table></div></section>
  </div>{showResults && <ResultsPanel onClose={() => setShowResults(false)} />}</SchoolShell>;
}

function ResultsPanel({ onClose }: { onClose: () => void }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-foreground/30 p-4 backdrop-blur-sm"><div className="glass-panel w-full max-w-md rounded-lg p-6 shadow-2xl"><BookOpenCheck className="size-6 text-primary" /><h2 className="mt-4 font-display text-xl font-bold">Term II results</h2><p className="mt-1 text-sm text-muted-foreground">Your latest published continuous-assessment results.</p><div className="mt-5 space-y-3">{results.map((result) => <div key={result.subject} className="flex items-center justify-between rounded-md border border-border bg-background/60 px-3 py-2.5"><span className="text-sm font-medium">{result.subject}</span><span className="text-sm">{result.score} · <strong>{result.grade}</strong></span></div>)}</div><div className="mt-6 flex justify-end"><Button onClick={onClose}>Close results</Button></div></div></div>; }
function Metric({ label, value, note }: { label: string; value: string; note: string }) { return <article className="glass-panel rounded-lg p-5"><p className="text-xs font-medium text-muted-foreground">{label}</p><p className="mt-2 font-display text-3xl">{value}</p><p className="mt-1 text-xs text-secondary-foreground">{note}</p></article>; }
