/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademicSetupRouteImport } from './routes/academic-setup'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AttendanceOverviewRouteImport } from './routes/attendance-overview'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as CouponsRouteImport } from './routes/coupons'
import { Route as DailyPaymentsRouteImport } from './routes/daily-payments'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as GradesRouteImport } from './routes/grades'
import { Route as GuestRouteImport } from './routes/guest'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ReconciliationRouteImport } from './routes/reconciliation'
import { Route as SchoolAdminRouteImport } from './routes/school-admin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StudentRouteImport } from './routes/student'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as TerminalReportsRouteImport } from './routes/terminal-reports'
import { Route as TeacherPromotionRouteImport } from './routes/teacher/promotion'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicSetupRoute = AcademicSetupRouteImport.update({
  id: '/academic-setup',
  path: '/academic-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceOverviewRoute = AttendanceOverviewRouteImport.update({
  id: '/attendance-overview',
  path: '/attendance-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsRoute = CouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyPaymentsRoute = DailyPaymentsRouteImport.update({
  id: '/daily-payments',
  path: '/daily-payments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const GradesRoute = GradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconciliationRoute = ReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolAdminRoute = SchoolAdminRouteImport.update({
  id: '/school-admin',
  path: '/school-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalReportsRoute = TerminalReportsRouteImport.update({
  id: '/terminal-reports',
  path: '/terminal-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherPromotionRoute = TeacherPromotionRouteImport.update({
  id: '/promotion',
  path: '/promotion',
  getParentRoute: () => TeacherRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academic-setup': typeof AcademicSetupRoute
  '/admin': typeof AdminRoute
  '/attendance': typeof AttendanceRoute
  '/attendance-overview': typeof AttendanceOverviewRoute
  '/classes': typeof ClassesRoute
  '/coupons': typeof CouponsRoute
  '/daily-payments': typeof DailyPaymentsRoute
  '/dashboard': typeof DashboardRoute
  '/finance': typeof FinanceRoute
  '/grades': typeof GradesRoute
  '/guest': typeof GuestRoute
  '/login': typeof LoginRoute
  '/parent': typeof ParentRoute
  '/payments': typeof PaymentsRoute
  '/reconciliation': typeof ReconciliationRoute
  '/school-admin': typeof SchoolAdminRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRoute
  '/students': typeof StudentsRoute
  '/subjects': typeof SubjectsRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/teachers': typeof TeachersRoute
  '/terminal-reports': typeof TerminalReportsRoute
  '/teacher/promotion': typeof TeacherPromotionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academic-setup': typeof AcademicSetupRoute
  '/admin': typeof AdminRoute
  '/attendance': typeof AttendanceRoute
  '/attendance-overview': typeof AttendanceOverviewRoute
  '/classes': typeof ClassesRoute
  '/coupons': typeof CouponsRoute
  '/daily-payments': typeof DailyPaymentsRoute
  '/dashboard': typeof DashboardRoute
  '/finance': typeof FinanceRoute
  '/grades': typeof GradesRoute
  '/guest': typeof GuestRoute
  '/login': typeof LoginRoute
  '/parent': typeof ParentRoute
  '/payments': typeof PaymentsRoute
  '/reconciliation': typeof ReconciliationRoute
  '/school-admin': typeof SchoolAdminRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRoute
  '/students': typeof StudentsRoute
  '/subjects': typeof SubjectsRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/teachers': typeof TeachersRoute
  '/terminal-reports': typeof TerminalReportsRoute
  '/teacher/promotion': typeof TeacherPromotionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academic-setup': typeof AcademicSetupRoute
  '/admin': typeof AdminRoute
  '/attendance': typeof AttendanceRoute
  '/attendance-overview': typeof AttendanceOverviewRoute
  '/classes': typeof ClassesRoute
  '/coupons': typeof CouponsRoute
  '/daily-payments': typeof DailyPaymentsRoute
  '/dashboard': typeof DashboardRoute
  '/finance': typeof FinanceRoute
  '/grades': typeof GradesRoute
  '/guest': typeof GuestRoute
  '/login': typeof LoginRoute
  '/parent': typeof ParentRoute
  '/payments': typeof PaymentsRoute
  '/reconciliation': typeof ReconciliationRoute
  '/school-admin': typeof SchoolAdminRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRoute
  '/students': typeof StudentsRoute
  '/subjects': typeof SubjectsRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/teachers': typeof TeachersRoute
  '/terminal-reports': typeof TerminalReportsRoute
  '/teacher/promotion': typeof TeacherPromotionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academic-setup'
    | '/admin'
    | '/attendance'
    | '/attendance-overview'
    | '/classes'
    | '/coupons'
    | '/daily-payments'
    | '/dashboard'
    | '/finance'
    | '/grades'
    | '/guest'
    | '/login'
    | '/parent'
    | '/payments'
    | '/reconciliation'
    | '/school-admin'
    | '/signup'
    | '/student'
    | '/students'
    | '/subjects'
    | '/teacher'
    | '/teachers'
    | '/terminal-reports'
    | '/teacher/promotion'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academic-setup'
    | '/admin'
    | '/attendance'
    | '/attendance-overview'
    | '/classes'
    | '/coupons'
    | '/daily-payments'
    | '/dashboard'
    | '/finance'
    | '/grades'
    | '/guest'
    | '/login'
    | '/parent'
    | '/payments'
    | '/reconciliation'
    | '/school-admin'
    | '/signup'
    | '/student'
    | '/students'
    | '/subjects'
    | '/teacher'
    | '/teachers'
    | '/terminal-reports'
    | '/teacher/promotion'
  id:
    | '__root__'
    | '/'
    | '/academic-setup'
    | '/admin'
    | '/attendance'
    | '/attendance-overview'
    | '/classes'
    | '/coupons'
    | '/daily-payments'
    | '/dashboard'
    | '/finance'
    | '/grades'
    | '/guest'
    | '/login'
    | '/parent'
    | '/payments'
    | '/reconciliation'
    | '/school-admin'
    | '/signup'
    | '/student'
    | '/students'
    | '/subjects'
    | '/teacher'
    | '/teachers'
    | '/terminal-reports'
    | '/teacher/promotion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademicSetupRoute: typeof AcademicSetupRoute
  AdminRoute: typeof AdminRoute
  AttendanceRoute: typeof AttendanceRoute
  AttendanceOverviewRoute: typeof AttendanceOverviewRoute
  ClassesRoute: typeof ClassesRoute
  CouponsRoute: typeof CouponsRoute
  DailyPaymentsRoute: typeof DailyPaymentsRoute
  DashboardRoute: typeof DashboardRoute
  FinanceRoute: typeof FinanceRoute
  GradesRoute: typeof GradesRoute
  GuestRoute: typeof GuestRoute
  LoginRoute: typeof LoginRoute
  ParentRoute: typeof ParentRoute
  PaymentsRoute: typeof PaymentsRoute
  ReconciliationRoute: typeof ReconciliationRoute
  SchoolAdminRoute: typeof SchoolAdminRoute
  SignupRoute: typeof SignupRoute
  StudentRoute: typeof StudentRoute
  StudentsRoute: typeof StudentsRoute
  SubjectsRoute: typeof SubjectsRoute
  TeacherRoute: typeof TeacherRouteWithChildren
  TeachersRoute: typeof TeachersRoute
  TerminalReportsRoute: typeof TerminalReportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic-setup': {
      id: '/academic-setup'
      path: '/academic-setup'
      fullPath: '/academic-setup'
      preLoaderRoute: typeof AcademicSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance-overview': {
      id: '/attendance-overview'
      path: '/attendance-overview'
      fullPath: '/attendance-overview'
      preLoaderRoute: typeof AttendanceOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons': {
      id: '/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof CouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-payments': {
      id: '/daily-payments'
      path: '/daily-payments'
      fullPath: '/daily-payments'
      preLoaderRoute: typeof DailyPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grades': {
      id: '/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof GradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciliation': {
      id: '/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof ReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school-admin': {
      id: '/school-admin'
      path: '/school-admin'
      fullPath: '/school-admin'
      preLoaderRoute: typeof SchoolAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal-reports': {
      id: '/terminal-reports'
      path: '/terminal-reports'
      fullPath: '/terminal-reports'
      preLoaderRoute: typeof TerminalReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/promotion': {
      id: '/teacher/promotion'
      path: '/promotion'
      fullPath: '/teacher/promotion'
      preLoaderRoute: typeof TeacherPromotionRouteImport
      parentRoute: typeof TeacherRoute
    }
  }
}

interface TeacherRouteChildren {
  TeacherPromotionRoute: typeof TeacherPromotionRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherPromotionRoute: TeacherPromotionRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademicSetupRoute: AcademicSetupRoute,
  AdminRoute: AdminRoute,
  AttendanceRoute: AttendanceRoute,
  AttendanceOverviewRoute: AttendanceOverviewRoute,
  ClassesRoute: ClassesRoute,
  CouponsRoute: CouponsRoute,
  DailyPaymentsRoute: DailyPaymentsRoute,
  DashboardRoute: DashboardRoute,
  FinanceRoute: FinanceRoute,
  GradesRoute: GradesRoute,
  GuestRoute: GuestRoute,
  LoginRoute: LoginRoute,
  ParentRoute: ParentRoute,
  PaymentsRoute: PaymentsRoute,
  ReconciliationRoute: ReconciliationRoute,
  SchoolAdminRoute: SchoolAdminRoute,
  SignupRoute: SignupRoute,
  StudentRoute: StudentRoute,
  StudentsRoute: StudentsRoute,
  SubjectsRoute: SubjectsRoute,
  TeacherRoute: TeacherRouteWithChildren,
  TeachersRoute: TeachersRoute,
  TerminalReportsRoute: TerminalReportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
